def and_gate(a, b, z):
    and_gate_dict = {
        ('Z', 'Z', 'Z'): {"gates": ('Z', 'Z', 'Z'), "error": '0', "change": '0'},
        ('Z', 'Z', '0'): {"gates": ('Z', 'Z', '0'), "error": '0', "change": '0'},
        ('Z', 'Z', '1'): {"gates": ('1', '1', '1'), "error": '0', "change": '1'},
        ('Z', '0', 'Z'): {"gates": ('Z', '0', '0'), "error": '0', "change": '1'},
        ('Z', '0', '0'): {"gates": ('Z', '0', '0'), "error": '0', "change": '0'},
        ('Z', '0', '1'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('Z', '1', 'Z'): {"gates": ('Z', '1', 'Z'), "error": '0', "change": '0'},
        ('Z', '1', '0'): {"gates": ('0', '1', '0'), "error": '0', "change": '1'},
        ('Z', '1', '1'): {"gates": ('1', '1', '1'), "error": '0', "change": '1'},
        ('0', 'Z', 'Z'): {"gates": ('0', 'Z', '0'), "error": '0', "change": '1'},
        ('0', 'Z', '0'): {"gates": ('0', 'Z', '0'), "error": '0', "change": '0'},
        ('0', 'Z', '1'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('0', '0', 'Z'): {"gates": ('0', '0', '0'), "error": '0', "change": '1'},
        ('0', '0', '0'): {"gates": ('0', '0', '0'), "error": '0', "change": '0'},
        ('0', '0', '1'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('0', '1', 'Z'): {"gates": ('0', '1', '0'), "error": '0', "change": '1'},
        ('0', '1', '0'): {"gates": ('0', '1', '0'), "error": '0', "change": '0'},
        ('0', '1', '1'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('1', 'Z', 'Z'): {"gates": ('1', 'Z', 'Z'), "error": '0', "change": '0'},
        ('1', 'Z', '0'): {"gates": ('1', '0', '0'), "error": '0', "change": '1'},
        ('1', 'Z', '1'): {"gates": ('1', '1', '1'), "error": '0', "change": '1'},
        ('1', '0', 'Z'): {"gates": ('1', '0', '0'), "error": '0', "change": '1'},
        ('1', '0', '0'): {"gates": ('1', '0', '0'), "error": '0', "change": '0'},
        ('1', '0', '1'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('1', '1', 'Z'): {"gates": ('1', '1', '1'), "error": '0', "change": '1'},
        ('1', '1', '0'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('1', '1', '1'): {"gates": ('1', '1', '1'), "error": '0', "change": '0'},
    }
    return and_gate_dict.get((a, b, z), {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'})

def xor_gate(a, b, z):
    xor_gate_dict = {
        ('Z', 'Z', 'Z'): {"gates": ('Z', 'Z', 'Z'), "error": '0', "change": '0'},
        ('Z', 'Z', '0'): {"gates": ('Z', 'Z', '0'), "error": '0', "change": '0'},
        ('Z', 'Z', '1'): {"gates": ('Z', 'Z', '1'), "error": '0', "change": '0'},
        ('Z', '0', 'Z'): {"gates": ('Z', '0', 'Z'), "error": '0', "change": '0'},
        ('Z', '0', '0'): {"gates": ('0', '0', '0'), "error": '0', "change": '1'},
        ('Z', '0', '1'): {"gates": ('1', '0', '1'), "error": '0', "change": '1'},
        ('Z', '1', 'Z'): {"gates": ('Z', '1', 'Z'), "error": '0', "change": '0'},
        ('Z', '1', '0'): {"gates": ('1', '1', '0'), "error": '0', "change": '1'},
        ('Z', '1', '1'): {"gates": ('0', '1', '1'), "error": '0', "change": '1'},
        ('0', 'Z', 'Z'): {"gates": ('0', 'Z', 'Z'), "error": '0', "change": '0'},
        ('0', 'Z', '0'): {"gates": ('0', '0', '0'), "error": '0', "change": '1'},
        ('0', 'Z', '1'): {"gates": ('0', '1', '1'), "error": '0', "change": '1'},
        ('0', '0', 'Z'): {"gates": ('0', '0', '0'), "error": '0', "change": '1'},
        ('0', '0', '0'): {"gates": ('0', '0', '0'), "error": '0', "change": '0'},
        ('0', '0', '1'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('0', '1', 'Z'): {"gates": ('0', '1', '1'), "error": '0', "change": '1'},
        ('0', '1', '0'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('0', '1', '1'): {"gates": ('0', '1', '1'), "error": '0', "change": '0'},
        ('1', 'Z', 'Z'): {"gates": ('1', 'Z', 'Z'), "error": '0', "change": '0'},
        ('1', 'Z', '0'): {"gates": ('1', '1', '0'), "error": '0', "change": '1'},
        ('1', 'Z', '1'): {"gates": ('1', '0', '1'), "error": '0', "change": '1'},
        ('1', '0', 'Z'): {"gates": ('1', '0', '1'), "error": '0', "change": '1'},
        ('1', '0', '0'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('1', '0', '1'): {"gates": ('1', '0', '1'), "error": '0', "change": '0'},
        ('1', '1', 'Z'): {"gates": ('1', '1', '0'), "error": '0', "change": '1'},
        ('1', '1', '0'): {"gates": ('1', '1', '0'), "error": '0', "change": '0'},
        ('1', '1', '1'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
    }
    return xor_gate_dict.get((a, b, z), {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'})

def or_gate(a, b, z):
    or_gate_dict = {
        ('Z', 'Z', 'Z'): {"gates": ('Z', 'Z', 'Z'), "error": '0', "change": '0'},
        ('Z', 'Z', '0'): {"gates": ('0', '0', '0'), "error": '0', "change": '1'},
        ('Z', 'Z', '1'): {"gates": ('Z', 'Z', '1'), "error": '0', "change": '0'},
        ('Z', '0', 'Z'): {"gates": ('Z', '0', 'Z'), "error": '0', "change": '0'},
        ('Z', '0', '0'): {"gates": ('0', '0', '0'), "error": '0', "change": '1'},
        ('Z', '0', '1'): {"gates": ('1', '0', '1'), "error": '0', "change": '1'},
        ('Z', '1', 'Z'): {"gates": ('Z', '1', '1'), "error": '0', "change": '1'},
        ('Z', '1', '0'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('Z', '1', '1'): {"gates": ('Z', '1', '1'), "error": '0', "change": '0'},
        ('0', 'Z', 'Z'): {"gates": ('0', 'Z', 'Z'), "error": '0', "change": '0'},
        ('0', 'Z', '0'): {"gates": ('0', '0', '0'), "error": '0', "change": '1'},
        ('0', 'Z', '1'): {"gates": ('0', '1', '1'), "error": '0', "change": '1'},
        ('0', '0', 'Z'): {"gates": ('0', '0', '0'), "error": '0', "change": '1'},
        ('0', '0', '0'): {"gates": ('0', '0', '0'), "error": '0', "change": '0'},
        ('0', '0', '1'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('0', '1', 'Z'): {"gates": ('0', '1', '1'), "error": '0', "change": '1'},
        ('0', '1', '0'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('0', '1', '1'): {"gates": ('0', '1', '1'), "error": '0', "change": '0'},
        ('1', 'Z', 'Z'): {"gates": ('1', 'Z', '1'), "error": '0', "change": '1'},
        ('1', 'Z', '0'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('1', 'Z', '1'): {"gates": ('1', 'Z', '1'), "error": '0', "change": '0'},
        ('1', '0', 'Z'): {"gates": ('1', '0', '1'), "error": '0', "change": '1'},
        ('1', '0', '0'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('1', '0', '1'): {"gates": ('1', '0', '1'), "error": '0', "change": '0'},
        ('1', '1', 'Z'): {"gates": ('1', '1', '1'), "error": '0', "change": '1'},
        ('1', '1', '0'): {"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'},
        ('1', '1', '1'): {"gates": ('1', '1', '1'), "error": '0', "change": '0'},
    }
    return or_gate_dict.get((a, b, z),{"gates": ('Z', 'Z', 'Z'), "error": '1', "change": '1'})
